# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d482b53f74e39e422157b4580653cf2220ff651923641de6b210bdb5f57695e375a191a20557868bef7c331e65acc248a0406f7558d891ac8dd563b056fd977

test:
  secret_key_base: f3a1dec25f5754af114e857c25b98ad3c926579b37a4061aadb0b8c342fe5cb4efcb5748207581aa1880bd63190f682bd05990a01824db47189f3a83bb0167de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
